todo/tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name='list'),
    path("atualizar/<str:pk>", views.updateTask, name="atualizar"),
    path("deletar/<str:pk>", views.deleteTask, name="deletar")
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('tasks.urls')),
    path('admin/', admin.site.urls),
]

todo/tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

todo/tasks/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields ='__all__'

todo/tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def index(request):
    tasks = Task.objects.all()
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context_dict={'tasks':tasks,'form':form}
    return render(request, 'tasks/index.html',context_dict)

def updateTask(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')
    context_dict = {'form':form}
    return render(request,'tasks/atualizar.html',context_dict)

def deleteTask(request,pk):
    item = Task.objects.get(id=pk)

    if request.method == "POST":
        item.delete()
        return redirect('/')

    context_dict = {'item':item}
    return render(request, 'tasks/deletar.html',context_dict)

todo/templates/tasks/atualizar.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Atualizar</title>
    <link rel="stylesheet" href="{% static "css/liststyle.css"%}">
    <link rel="stylesheet" href="https://unpkg.com/98.css">
  </head>
  <body>
    <div class="window center-column">
      <div class="title-bar">
        <div class="title-bar-text">Atualizar</div>
        <div class="title-bar-controls">
          <button aria-label="Minimize"></button>
          <button aria-label="Maximize"></button>
          <button aria-label="Close"></button>
        </div>
      </div>
      <div class="window-body">
        <form method="POST" id="form3" action="">
          {% csrf_token %}

          <label for="id_title">Titulo</label>{{form.title}}
          {{form.complete}}<label for="id_complete">Completo: </label>
        </form>
        <button id='excluir' type="submit" form="form3" value="Submit">Atualizar</button>
      </div>
    </div>
  </body>
</html>

todo/templates/tasks/deletar.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Deletar</title>
    <link rel="stylesheet" href="{% static "css/liststyle.css"%}">
    <link rel="stylesheet" href="https://unpkg.com/98.css">
  </head>
  <body>
    <div class="window center-column">
      <div class="title-bar">
        <div class="title-bar-text">Exclusão</div>
        <div class="title-bar-controls">
          <button aria-label="Minimize"></button>
          <button aria-label="Maximize"></button>
          <button aria-label="Close"></button>
        </div>
      </div>
      <div class="window-body">
        <p>Tem certeza que deseja excluir "{{item}}" ?</p>
        <a href="{% url 'list'%}"><button>Cancelar</button></a>
        <form method="post" id='form2' action="">
          {% csrf_token %}
        </form>
        <button id='excluir' type="submit" form="form2" value="Submit">Excluir</button>
      </div>
    </div>
  </body>
</html>

todo/templates/tasks/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Lista de Afazeres</title>
    <link rel="stylesheet" href="{% static "css/liststyle.css"%}">
    <link rel="stylesheet" href="https://unpkg.com/98.css">
  </head>
  <body>
    <!-- Div Central -->
    <div class="window center-column" id="principal">
      <div class="title-bar">
        <div class="title-bar-text">Afazeres</div>
        <div class="title-bar-controls">
          <button aria-label="Minimize"></button>
          <button aria-label="Maximize"></button>
          <button aria-label="Close"></button>
        </div>
      </div>
      <!-- Menu de Criação -->
      <div class="window-body">
        <form method="POST" id="form1" action="/">
          {% csrf_token %}
          {{form.title}}
        </form>
        <button id="cria" type="submit" form="form1" value="Submit">Criar</button>
      <!-- Fim Menu de Criação -->

      <!-- Carregamento das Tasks -->
        {% for task in tasks %}
            <div class="window task">
            <div class="title-bar"
            {% if task.complete == True %}
              style="background: red;"
            {% endif %}>
              <div class="title-bar-text">{{task}}
                {% if task.complete == True %}
                  (COMPLETA)
                {% endif %}
            </div>
              <div class="title-bar-controls">
                <button aria-label="Minimize"></button>
                <button aria-label="Maximize"></button>
                <a href="{% url 'deletar' task.id %}"><button aria-label="Close"></button></a>
              </div>
            </div>
            <div class="window-body">
              <a href="{% url 'atualizar' task.id %}"><button>Atualizar</button></a>
              <a href="{% url 'deletar' task.id %}"><button>Excluir</button></a>
            </div>
          </div>
      {% endfor %}
      <!-- Fim do carregamento das Tasks -->
      </div>
    </div>
    <!-- Fim da div Central-->
  </body>
</html>